### ISSUE TITLE
Unable to complete "configure"

### ISSUE THREAD

**Issue by jonapich** [InnovativeTravel/humilis#10] opened 2016-04-27 18:35 UTC
When running --configure, we have to provide an s3 bucket as argument. Then it breaks:

E:\humilis>humilis configure
Bucket [None]: mysupertestbucket
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\humilis.exe__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "c:\python27\lib\site-packages\humilis\cli.py", line 124, in configure
    config.boto_config.configure(ask=ask, local=local)
  File "c:\python27\lib\site-packages\boto3facade\config.py", line 73, in configure
    self._get_config(option, ask=ask, fallback=fallback)
  File "c:\python27\lib\site-packages\boto3facade\config.py", line 121, in _get_config
    option.replace('_', ' ').title(), val))
  File "<string>", line 1, in <module>
NameError: name 'mysupertestbucket' is not defined

**Comment by jonapich** [comment] 2016-04-27 18:37
There is no mention in the readme about how to configure AWS credentials. It's probably what's missing here.

Boto3 works wonder. Is this something specific to facade that I have to do?

**Comment by germangh** [comment] 2016-04-27 19:07
I see that you are running this under Windows which is a platform I have never used with humilis. I assume you are using the latest version (0.4.4)? Just to make sure please run `pip install humilis --upgrade`. And to double check please tell me what you get if you run this in a Python CLI:

```
import humilis
humilis.__version__
import boto3facade
boto3facade.__version__
```

What do you get if you run this?

```
humilis configure --local
```

That should create a `.humilis.ini` configuration file in your working directory with the configuration options. Running simply `humilis configure` tries to create the file under your home directory instead. If humilis finds a `.humilis.ini` in your working directory, then it takes preference over any file you may also have in your home dir.

Regarding the AWS credentials. You need to have the AWS CLI installed in your system (`pip install awscli`) and configured using:

```
aws configure
```

I'll add this important information to the README. `humilis` simply uses the AWS credentials that you have configured with the AWS CLI. When `humilis configure` asks you for an AWS profile you should use whatever AWS CLI profile you want to use to access AWS services (most likely: `default`).

**Comment by jonapich** [comment] 2016-04-27 19:23
I had already tried the --local switch with resulted in the same behavior.

Here's the output you requested:

```
>>> import humilis
>>> humilis.__version__
'0.4.4'
>>> import boto3facade
>>> boto3facade.__version__
'0.2.1'
```

I don't have the awscli package, so that explains a lot. When I have a minute I'll try it out and let you know how it worked out.

Thanks for the quick reply!

**Comment by jonapich** [comment] 2016-04-27 20:14
By the way, the link in the readme is wrong:

pip install git+https://github.com/germangh/humilis

It should be humilis/humilis.

**Comment by jocgir** [comment] 2016-04-27 21:04
When running **humilis configure**, I got

Traceback (most recent call last):
  File "/usr/local/bin/humilis", line 9, in <module>
    load_entry_point('humilis==0.4.4', 'console_scripts', 'humilis')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2709, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2369, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2375, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/local/lib/python2.7/site-packages/humilis/cli.py", line 9, in <module>
    from humilis.config import config
  File "/usr/local/lib/python2.7/site-packages/humilis/config.py", line 124, in <module>
    config = Config('default')
  File "/usr/local/lib/python2.7/site-packages/humilis/config.py", line 92, in **init**
    fallback={'s3prefix': 'humilis'})
  File "/usr/local/lib/python2.7/site-packages/boto3facade/config.py", line 55, in **init**
    self.load()
  File "/usr/local/lib/python2.7/site-packages/boto3facade/config.py", line 147, in load
    self.profile = self.get_profile(self.active_profile)
  File "/usr/local/lib/python2.7/site-packages/boto3facade/config.py", line 166, in get_profile
    if section not in self.config:
TypeError: argument of type 'instance' is not iterable

**Comment by germangh** [comment] 2016-04-29 07:52
@jocgir I can't reproduce the error. Can you do the following and tell me the output you get:

```
rm -f ~/.humilis
import humilis
humilis.__version__
import boto3facade
boto3facade.__version__
```

After that, could you try running humilis in a virtual env (`pip install virtualenv`) and see if you still get the error:

```
virtualenv .env -p python2.7
. .env/bin/activate
pip install humilis
humilis configure
```

**Comment by jocgir** [comment] 2016-04-29 16:34
OK, it is working. When I reinstalled humilis, I did'nt force upgrade of boto3facade (witch was not working with Python2.7).

Thanks!

**Comment by germangh** [comment] 2016-04-29 16:54
cool, I am closing this issue then. @muikrad please reopen it if you are still having problems.

**Closed as completed by germangh** 2016-04-29 16:54 UTC

**Comment by jonapich** [comment] 2016-04-30 12:51
Even if I made it work, I don't think it would work fully; for instance I noticed super() calls in the code that uses the python 3 syntax and are invalid in python 2. I haven't done a deep analysis of the code but it feels like this is really a py3 package.

On a different topic, the way you are loading the jinja templates limits their functionality: imports and includes will break, for instance.

Good luck with your project; I found it very inspiring and there are lots of great ideas.

**Comment by germangh** [comment] 2016-04-30 13:31
Yes you are right, we never used humilis with Python 2.x until you posted the issue with `humilis configure`. But the current version will probably work under Python 2.x. The tests are passing at least, but considering how few tests we have right now, that's not a great assurance indeed. Thanks for reporting those `super()` calls. I just fixed that.

And regarding Jinja2 you are right as well of course. That should be fixed in the latest version though. The layer root directory is now a Jinja2 environment so you can use includes relative to that dir.

Thanks also for the good wishes!
